config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :beers, only: [:index, :show]

  get 'search_results', to: 'search#results', as: 'search_results'

  root to: 'beers#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :category # By way of a category_id FK.

  validates :name, :alcohol, :ibu, :price, presence: true
  validates :price, numericality: true

  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :beers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = Beer.order('id DESC')
  end
  # So the @beers variable will be shared with
  # the app/views/beers/index.html.erb

  # GET /beers/:id
  def show
    @beer = Beer.find(params[:id])
  end
  # The @beer variable will be shared with
  # the app/views/beers/show.html.erb
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    @query = params[:query]
    @beers = Beer.where('name LIKE ?', "%#{@query}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/beers/_beer.html.erb
<div class="beer">
  <% if show_links %>
    <h3><%= link_to beer.name, beer %></h3>
  <% else %>
    <h3><%= beer.name %></h3>
  <% end %>
  <p>Category: <%= beer.category.name %></p>
  <p>Price: <%= number_to_currency beer.price %></p>
  <p>Alcohol: <%= beer.alcohol %></p>
  <p>IBU: <%= beer.ibu %></p>
  <% if beer.image? %>
    <p><%= image_tag beer.image.thumbnail.url %></p>
  <% end %>
</div>

app/views/beers/index.html.erb
<h1>Tasty Beers For Sale</h1>

<%= render partial: 'beers/beer',
            collection: @beers,
            locals: {show_links: true } %>

app/views/beers/show.html.erb
<%= render partial: 'beers/beer',
            object: @beer,
            locals: {show_links: false} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= form_tag(search_results_path, method: "get") do %>
      <%= label_tag(:query, "Search for:") %>
      <%= text_field_tag(:query) %>
      <%= submit_tag("Search") %>
    <% end %>
    <!--
      When the form is submitted with the input as "test query" it results in:
      /search_results?utf8=%E2%9C%93&q=test+query&commit=Search
    -->

    <%= yield %>
  </body>
</html>

app/views/search/results.html.erb
<h1>Search Results</h1>

<h2>Your query for "<%= @query %>" returned <%= pluralize(@beers.size, 'result') %>.</h2>

<%= render partial: 'beers/beer',
            collection: @beers,
            locals: {show_links: true } %>